#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="/usr/local/Cellar/emacs-plus/26.3/bin:$PATH"
export PATH="/usr/local/Cellar/tmux/3.0a_1/bin:$PATH"

# java
export PATH="$HOME/.jenv/bin:$HOME/.jenv/shims:$PATH"
eval "$(jenv init -)"

# export JAVA_HOME=/Applications/OpenJDK/jdk8u144-b01

# andriod
export ANDROID_HOME="$HOME/Library/android/sdk"

# python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Yarn
export PATH="/usr/local/bin:$PATH"

# node
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
# nvm use default

export PATH="/Users/martinrichards/.bin:$PATH"

# scala bloop
export PATH="/Users/martinrichards/.bloop:$PATH"
autoload -U compinit
fpath=($HOME/.bloop/zsh $fpath)
compinit

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# emacs
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias vim='emacsclient -t'
alias vi='emacsclient -t'
export EDITOR="ec"

destroy() {
  ps aux | grep "$*" | awk '{print $2}' | xargs kill -9;
}

# z - jump around
. /usr/local/etc/profile.d/z.sh

# YOCO
export TEST_JDBC_URL="postgres://yoco:password@localhost:5432/yoco_core_test"

autoload -U promptinit; promptinit
prompt pure

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/martinrichards/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/martinrichards/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/martinrichards/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/martinrichards/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh

# Azure
# autoload bashcompinit && bashcompinit
# source '/Users/martinrichards/lib/azure-cli/az.completion'

export PATH=$PATH:/usr/local/bin

## Google Cloud
export GOOGLE_APPLICATION_CREDENTIALS='$HOME/.gcp.credentials.json'
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/martinrichards/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/martinrichards/Downloads/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/martin/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/martin/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# Kubernetes
# kubectl completion zsh > "${fpath[1]}/_kubectl"export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"
export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"
alias lzd='lazydocker'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/martin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/martin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/martin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/martin/google-cloud-sdk/completion.zsh.inc'; fi

# OPENSSL
export PATH="/usr/local/opt/openssl/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

# fnm
eval "$(fnm env --multi)"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


# https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1
ulimit -S -n 2048

# ncurses
export PATH="/usr/local/opt/ncurses/bin:$PATH"
